# @Author: Felipe Gonçalves Marques
# @Date:   2016-11-12 09:11:09
# @Email:  marques.goncalves.felipe@gmail.com
# @Last modified by:   Felipe Gonçalves Marques
# @Last modified time: 2016-11-12 20:11:57

# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d8c187c67cab3772a6293ffc02d933a75c36fb1fe3d402a86354442f1fb4a02107edc91e1f5a9df82a357ce28fe9aa8f3441dfd775238504fe2eb3bad7df6a
  superuser_login: test
  superuser_password: test
test:
  secret_key_base: 265fc42ec4bde5a95d01981dc0019892ee8c7cc3ff4fdae358fdd610449a2827c4f7c0c66477f7cb5a2fc7f3c7f412a8ba264f89499cd4075605aaf4f98a07ac
  superuser_login: test
  superuser_password: test
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  superuser_login: senec_administrator
  superuser_password: UIXcl
